import { FormEvent, useState } from 'react';
import { Activity, ArrowRight, ShieldCheck } from 'lucide-react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { useNocStore } from '../store/useNocStore';
import { loginApi } from '../api/auth';
import { ApiError } from '../lib/apiClient';
export function LegacyLoginPage(){
 const user=useNocStore(s=>s.currentUser); const login=useNocStore(s=>s.login); const [username,setUsername]=useState('operator');const[password,setPassword]=useState('NocLocal!2026');const[error,setError]=useState('');const nav=useNavigate();
 if(user)return <Navigate to="/dashboard"/>;
 const submit=(e:FormEvent)=>{e.preventDefault();if(login(username,password))nav('/dashboard');else setError('帳號、密碼錯誤，或帳號尚未啟用。')};
 return <div className="auth-page"><section className="auth-hero"><div className="brand large"><div className="brand-mark"><Activity/></div><b>NOC Network<br/>Incident Copilot</b></div><div><span className="eyebrow">SIMULATION PLATFORM</span><h1>從告警到結報，<br/><em>讓每一步都有依據。</em></h1><p>專為展示與學習打造的網路障礙監控與事件處理模擬平台。</p></div><div className="safe"><ShieldCheck/><span><b>安全模擬環境</b><small>不連接真實設備、網路或 API</small></span></div></section>
 <section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><span className="eyebrow">WELCOME BACK</span><h2>登入 NOC 指揮台</h2><p>使用本機核准帳號進入對應工作流程。</p><label>帳號<input value={username} onChange={e=>setUsername(e.target.value)} required autoFocus/></label><label>密碼<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><div className="form-between"><label className="check"><input type="checkbox" defaultChecked/>記住我</label></div>{error&&<div className="form-error">{error}</div>}<button className="btn primary wide">登入系統 <ArrowRight/></button><div className="demo-grid">{[['operator','一線人員'],['engineer','設備管理員'],['admin','系統管理員']].map(([u,l])=><button type="button" key={u} onClick={()=>{setUsername(u);setPassword('NocLocal!2026')}}><b>{l}</b><small>{u}</small></button>)}</div><p className="center">尚無帳號？ <Link to="/register">申請註冊</Link></p></form></section></div>
}
export function LoginPage(){
 const user=useNocStore(s=>s.currentUser),loginApiUser=useNocStore(s=>s.loginApiUser);const[username,setUsername]=useState('operator'),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);const nav=useNavigate();
 if(user)return <Navigate to="/dashboard"/>;
 const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{const result=await loginApi(username,password);localStorage.setItem('noc-access-token',result.access_token);loginApiUser(result.user);nav('/dashboard')}catch(apiError){setError(apiError instanceof ApiError?apiError.message:'帳號或密碼錯誤')}finally{setLoading(false)}};
 return <div className="auth-page"><section className="auth-hero"><div className="brand large"><div className="brand-mark"><Activity/></div><b>NOC Network<br/>Incident Copilot</b></div><div><span className="eyebrow">OPERATIONS PLATFORM</span><h1>網路事件管理<br/><em>快速、清楚、可追蹤</em></h1><p>整合即時告警、設備管理、拓樸分析與權限控管。</p></div><div className="safe"><ShieldCheck/><span><b>安全的角色權限</b><small>透過 FastAPI JWT 驗證登入身分</small></span></div></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><span className="eyebrow">WELCOME BACK</span><h2>登入 NOC 平台</h2><p>使用已核准的帳號登入；資料服務離線時保留最後同步狀態。</p><label>帳號或 Email<input value={username} onChange={e=>setUsername(e.target.value)} required autoFocus/></label><label>密碼<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="form-error">{error}</div>}<button className="btn primary wide" disabled={loading}>{loading?'登入中…':<>登入平台 <ArrowRight/></>}</button><div className="demo-grid">{[['operator','NOC Operator'],['engineer','Device Manager'],['admin','System Admin']].map(([u,l])=><button type="button" key={u} onClick={()=>setUsername(u)}><b>{l}</b><small>{u}</small></button>)}</div><p className="center">還沒有帳號？<Link to="/register">申請註冊</Link></p></form></section></div>;
}

export function RegisterPage(){
 const register=useNocStore(s=>s.register);const nav=useNavigate();const [form,setForm]=useState({name:'',employeeId:'',email:'',teams:'',phone:'',department:'',role:'operator',password:'',confirm:''});
 const submit=(e:FormEvent)=>{e.preventDefault();if(form.password!==form.confirm)return alert('兩次密碼不一致');register({id:crypto.randomUUID(),username:form.employeeId,password:form.password,name:form.name,employeeId:form.employeeId,email:form.email,teams:form.teams,phone:form.phone,department:form.department,role:form.role as 'operator',status:'等待審核'});alert('申請已送出，狀態為等待審核');nav('/login')};
 return <div className="simple-page"><form className="card form-grid register" onSubmit={submit}><h1>申請 NOC 帳號</h1><p>送出後需由系統管理員審核。</p>{[['name','姓名'],['employeeId','員工編號（登入帳號）'],['email','Email'],['teams','Teams 帳號'],['phone','手機'],['department','部門']].map(([k,l])=><label key={k}>{l}<input required value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>申請角色<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="operator">一線人員</option><option value="engineer">設備管理員</option></select></label><label>密碼<input required minLength={6} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>確認密碼<input required type="password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></label><div className="form-actions"><Link className="btn" to="/login">返回登入</Link><button className="btn primary">送出申請</button></div></form></div>
}
