import { FormEvent, useMemo, useState } from 'react';
import { Bell, Check, Clipboard, Copy, ExternalLink, Filter, GitBranch, MessageSquarePlus, Phone, Plus, Search, Send, ShieldAlert, Trash2, UserCheck, X } from 'lucide-react';
import { contacts, topologyLinks, topologyNodes } from '../data/mockData';
import { useNocStore } from '../store/useNocStore';
import type { Alarm, IncidentStatus } from '../types';
import { Badge, Card, Empty, severityTone, Status } from '../components/common/UI';
import { DiagnosisPanel } from '../components/diagnosis/DiagnosisPanel';
import { TestRunner } from '../components/testing/TestRunner';

export function AlarmPage(){
 const alarms=useNocStore(s=>s.alarms),selectedId=useNocStore(s=>s.selectedAlarmId),select=useNocStore(s=>s.selectAlarm),regionFilter=useNocStore(s=>s.regionFilter),setRegion=useNocStore(s=>s.setRegionFilter); const [q,setQ]=useState(''),[sev,setSev]=useState(''),[status,setStatus]=useState('');
 const filtered=alarms.filter(a=>(!q||Object.values(a).join(' ').toLowerCase().includes(q.toLowerCase()))&&(!sev||a.severity===sev)&&(!regionFilter||a.region===regionFilter)&&(!status||a.status===status)); const selected=alarms.find(a=>a.id===selectedId)??filtered[0];
 return <div className="page"><div className="page-title"><div><span className="eyebrow">ALARM COMMAND CENTER</span><h1>告警中心</h1><p>篩選、判讀並追蹤所有模擬告警。</p></div><Badge tone="critical">{alarms.filter(a=>a.status!=='已恢復').length} 筆作用中</Badge></div>
 <div className="toolbar"><label className="search"><Search/><input placeholder="搜尋設備、IP、告警內容…" value={q} onChange={e=>setQ(e.target.value)}/></label><Filter/><select value={sev} onChange={e=>setSev(e.target.value)}><option value="">所有嚴重度</option>{['Critical','Major','Minor','Warning','Normal'].map(x=><option key={x}>{x}</option>)}</select><select value={regionFilter} onChange={e=>setRegion(e.target.value)}><option value="">所有區域</option>{[...new Set(alarms.map(a=>a.region))].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">所有狀態</option>{[...new Set(alarms.map(a=>a.status))].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="split"><Card className="alarm-list" title={`告警列表（${filtered.length}）`}>{filtered.length?filtered.map(a=><button className={`alarm-item ${selected?.id===a.id?'selected':''}`} key={a.id} onClick={()=>select(a.id)}><div className={`sev-line ${severityTone(a.severity)}`}/><div><span><Badge tone={severityTone(a.severity)}>{a.severity}</Badge><b>{a.deviceName}</b></span><strong>{a.content}</strong><small>{a.id} · {a.region}/{a.site} · {a.time}</small></div><Status status={a.maintenance?'maintenance':a.status==='已恢復'?'normal':'incident'}/></button>):<Empty text="沒有符合條件的告警"/>}</Card>
 <aside className="right-stack">{selected&&<AlarmDetail alarm={selected}/>}<DiagnosisPanel alarm={selected}/></aside></div></div>
}
function AlarmDetail({alarm}:{alarm:Alarm}){const device=useNocStore(s=>s.devices.find(d=>d.id===alarm.deviceId));return <Card title="告警詳細資料"><div className="detail-head"><Badge tone={severityTone(alarm.severity)}>{alarm.severity}</Badge><Status status={device?.status??'unknown'}/></div><h3>{alarm.content}</h3><dl className="detail-grid"><dt>設備</dt><dd>{alarm.deviceName}</dd><dt>IP 位址</dt><dd>{alarm.ip}</dd><dt>類型</dt><dd>{alarm.deviceType}</dd><dt>區域／局名</dt><dd>{alarm.region}／{alarm.site}</dd><dt>來源</dt><dd>{alarm.source}</dd><dt>負責人</dt><dd>{alarm.owner}</dd></dl>{device?.maintenance&&<div className="maintenance-note"><b>{device.maintenance.type}</b><br/>{device.maintenance.content}<br/>{device.maintenance.start}–{device.maintenance.end} · {device.maintenance.ticket}<br/>{device.maintenance.note}</div>}</Card>}

const states:IncidentStatus[]=['收到告警','AI 分析完成','查測中','等待設備管理員','確認原因','初報完成','持續追蹤','設備恢復','結報完成','事件關閉'];
export function IncidentsPage(){
 const incidents=useNocStore(s=>s.incidents),alarms=useNocStore(s=>s.alarms),update=useNocStore(s=>s.updateIncident),add=useNocStore(s=>s.addTimeline),notify=useNocStore(s=>s.notify);const[selected,setSelected]=useState(incidents[0]?.id??'');const[note,setNote]=useState('');const i=incidents.find(x=>x.id===selected)??incidents[0];const alarm=alarms.find(a=>a.incidentId===i?.id);
 const notification=(type:'初報'|'續報'|'結報')=>type==='初報'?`【網路障礙初報】\n事件編號：${i.id}\n發生時間：${i.started}\n障礙設備：${i.deviceId}\n告警內容：${alarm?.content}\n影響範圍：${i.affectedDevices} 台下游設備\n初步判斷：${i.cause}\n處理進度：${i.status}\n下次更新：30 分鐘內`:type==='續報'?`【網路障礙續報】\n事件編號：${i.id}\n目前原因：${i.cause}\n處理進度：${i.status}\n目前影響：${i.affectedDevices} 台設備\n預計恢復：評估中`:`【網路障礙結報】\n事件編號：${i.id}\n障礙原因：${i.cause}\n處理方式：更換 SFP 光模組\n影響設備：${i.affectedDevices} 台\n目前狀態：服務已恢復，告警已清除`;
 const [report,setReport]=useState<'初報'|'續報'|'結報'>('初報'); const [custom,setCustom]=useState('');
 if(!i)return <div className="page"><Empty text="目前沒有事件"/></div>;
 return <div className="page"><div className="page-title"><div><span className="eyebrow">INCIDENT LIFECYCLE</span><h1>事件中心</h1><p>從告警接收到結報關閉，全程留下紀錄。</p></div></div><div className="incident-tabs">{incidents.map(x=><button key={x.id} className={x.id===i.id?'active':''} onClick={()=>setSelected(x.id)}><Badge tone={severityTone(x.severity)}>{x.severity}</Badge><b>{x.title}</b><small>{x.id}</small></button>)}</div>
 <Card title={i.title} action={<Badge tone="info">{i.status}</Badge>}><div className="stepper">{states.map((s,n)=>{const current=states.indexOf(i.status);return <div className={n<current?'done':n===current?'current':''} key={s}><i>{n<current?<Check size={14}/>:n+1}</i><span>{s}</span></div>})}</div><div className="toolbar"><select value={i.status} onChange={e=>update(i.id,e.target.value as IncidentStatus,'')} >{states.map(s=><option key={s}>{s}</option>)}</select><input placeholder="狀態更新備註" value={note} onChange={e=>setNote(e.target.value)}/><button className="btn" onClick={()=>{update(i.id,i.status,note||'新增處理備註');setNote('')}}>更新紀錄</button></div></Card>
 <div className="split equal"><Card title="事件時間軸" action={<button className="btn small" onClick={()=>{const t=prompt('輸入時間軸紀錄');if(t)add(i.id,t)}}><MessageSquarePlus/>新增</button>}><div className="timeline">{i.timeline.length?i.timeline.map(t=><div key={t.id}><i/><time>{t.time}</time><span><b>{t.text}</b><small>{t.actor}{t.from&&` · ${t.from} → ${t.to}`}</small></span></div>):<Empty/>}</div></Card>
 <Card title="Teams 通報產生器"><div className="segment">{(['初報','續報','結報'] as const).map(x=><button className={report===x?'active':''} onClick={()=>{setReport(x);setCustom('')}} key={x}>{x}</button>)}</div><textarea rows={12} value={custom||notification(report)} onChange={e=>setCustom(e.target.value)}/><div className="form-actions"><button className="btn primary" onClick={()=>navigator.clipboard.writeText(custom||notification(report)).then(()=>notify(`已複製${report}`))}><Copy/>一鍵複製</button><button className="btn" onClick={()=>add(i.id,`已產生並記錄${report}`)}><Clipboard/>加入時間軸</button></div><p className="disclaimer">僅產生模擬文字，不連接 Microsoft Teams API。</p></Card></div>
 <div className="split equal"><TestRunner incidentId={i.id}/><ContactPanel incidentId={i.id}/></div></div>
}
function ContactPanel({incidentId}:{incidentId:string}){const notify=useNocStore(s=>s.notify),add=useNocStore(s=>s.addTimeline);return <Card title="設備管理員聯絡資訊"><div className="contacts">{contacts.map(c=><div key={c.id}><b>第{['一','二','三'][c.priority-1]}順位 · {c.name}</b><span>{c.role} · {c.status}</span><small><Phone/> {c.phone}<br/><Send/> {c.teams}</small><div><button className="btn small" onClick={()=>navigator.clipboard.writeText(`${c.name}\n${c.phone}\n${c.teams}`).then(()=>notify('已複製聯絡資訊'))}><Copy/>複製</button><button className="btn small" onClick={()=>{add(incidentId,`已通知第${c.priority}順位 ${c.name}`);notify('通知時間已記錄')}}><UserCheck/>標記已通知</button></div></div>)}</div><p className="disclaimer">所有姓名與聯絡資訊皆為展示用假資料。</p></Card>}

export function DiagnosisPage(){const alarms=useNocStore(s=>s.alarms),id=useNocStore(s=>s.selectedAlarmId),select=useNocStore(s=>s.selectAlarm);const a=alarms.find(x=>x.id===id)??alarms[0];return <div className="page"><div className="page-title"><div><span className="eyebrow">RULE-BASED COPILOT</span><h1>AI 診斷工作台</h1><p>依模擬告警與查測規則產生可解釋的處理建議。</p></div></div><div className="toolbar"><select value={a?.id} onChange={e=>select(e.target.value)}>{alarms.map(x=><option value={x.id} key={x.id}>{x.id} · {x.deviceName}</option>)}</select></div><div className="split equal"><DiagnosisPanel alarm={a}/><TestRunner incidentId={a?.incidentId}/></div></div>}
